name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Default branch
  pull_request:
    branches:
      - main  # Default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Build and test
      continue-on-error: true  # Continue even if this step fails
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      if: success()  # Only run this step if the build step succeeded
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
